# PANDAS

Es una libreria para manipular y tratar datos

##DATAFRAME

In [3]:
import pandas as pd
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []

In [26]:
nombres=('Eli','Almu','Bea','Luis', 'Jorge', 'Hector')
personas=pd.DataFrame(nombres)
print(personas)
personas[0]

        0
0     Eli
1    Almu
2     Bea
3    Luis
4   Jorge
5  Hector

0       Eli
1      Almu
2       Bea
3      Luis
4     Jorge
5    Hector
Name: 0, dtype: object

In [7]:
personas=pd.DataFrame(nombres, columns=['nombre'])
print(personas)

   nombre
0     Eli
1    Almu
2     Bea
3    Luis
4   Jorge
5  Hector

In [9]:
personas=( ('Eli' , 32), ('Almu',29) ,('Bea',30), ('Luis',33), ('Jorge',27), ('Hector', 29) )
personas=pd.DataFrame(personas, columns=['nombre','edad'])
print(personas)

   nombre  edad
0     Eli    32
1    Almu    29
2     Bea    30
3    Luis    33
4   Jorge    27
5  Hector    29

In [10]:
personas={ 'nombre': ['Eli','Almu','Bea', 'Luis','Jorge', 'Hector'], 'edad': [32,29,30,33,27,29] }
personas=pd.DataFrame(personas)
print(personas)

   nombre  edad
0     Eli    32
1    Almu    29
2     Bea    30
3    Luis    33
4   Jorge    27
5  Hector    29

In [11]:
eli={'nombre': 'Eli', 'edad':32}
almu={'nombre': 'Almu', 'edad':29}
bea={'nombre': 'Bea', 'edad':30}
lista=[eli, almu, bea]
personas=pd.DataFrame(lista)
print(personas)

  nombre  edad
0    Eli    32
1   Almu    29
2    Bea    30

In [41]:
# Cargar unos datos de un fichero
incendios=pd.read_csv(r'/Users/ivan/Downloads/California_Fire_Incidents.csv')

In [42]:
incendios.head(2)

,AcresBurned,Active,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
0,257314.0,False,Stanislaus National Forest/Yosemite National Park,NaN,2013,True,/incidents/2013/8/17/rim-fire/,NaN,NaN,Tuolumne,...,"Rim Fire, Stanislaus National Forest, Yosemite...",2013-08-17T15:25:00Z,Finalized,NaN,NaN,NaN,NaN,5fb18d4d-213f-4d83-a179-daaf11939e78,2013-09-06T18:30:00Z,NaN
1,30274.0,False,USFS Angeles National Forest/Los Angeles Count...,NaN,2013,True,/incidents/2013/5/30/powerhouse-fire/,NaN,NaN,Los Angeles,...,"Powerhouse Fire, May 2013, June 2013, Angeles ...",2013-05-30T15:28:00Z,Finalized,NaN,NaN,NaN,NaN,bf37805e-1cc2-4208-9972-753e47874c87,2013-06-08T18:30:00Z,NaN

In [43]:
incendios.tail(3)

,AcresBurned,Active,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
1633,NaN,False,Yolo County Fire Protection District,NaN,2019,False,/incidents/2019/11/25/cashe-fire/,NaN,NaN,Yolo,...,NaN,2019-11-25T12:02:02Z,Finalized,NaN,NaN,NaN,NaN,9c26f915-1b33-422d-b30a-9eb4da6fd729,2019-12-03T16:35:20.93Z,NaN
1634,NaN,False,Camp Pendleton Marine Corps Base,NaN,2019,False,/incidents/2019/10/22/oak-fire/,NaN,NaN,San Diego,...,NaN,2019-10-22T19:20:44Z,Finalized,NaN,NaN,NaN,NaN,7264a106-e0f4-41de-8fd0-3f9110431e28,2019-11-21T12:21:28.58Z,NaN
1635,NaN,False,Bureau of Indian Affairs,NaN,2019,False,/incidents/2019/10/14/johnson-fire/,"As of 10:00 p.m. on 10/16, the fire is 90% con...",NaN,Riverside,...,NaN,2019-10-14T15:32:20Z,Inactive,NaN,NaN,NaN,NaN,8bf75401-999f-42bd-8c0a-8db508591545,2019-10-30T10:14:19.58Z,NaN

In [44]:
incendios.ndim
incendios.shape
incendios.size

65440

In [45]:
incendios['Active']

0       False
1       False
2       False
3       False
4       False
        ...
1631    False
1632    False
1633    False
1634    False
1635    False
Name: Active, Length: 1636, dtype: bool

In [46]:
incendios.iloc[3]

AcresBurned                                                         27440
Active                                                              False
AdminUnit                                           Tahoe National Forest
AirTankers                                                            NaN
ArchiveYear                                                          2013
CalFireIncident                                                     False
CanonicalUrl                          /incidents/2013/8/10/american-fire/
ConditionStatement                                                    NaN
ControlStatement                                                      NaN
Counties                                                           Placer
CountyIds                                                              31
CrewsInvolved                                                         NaN
Dozers                                                                NaN
Engines                                                               NaN
Extinguished                                         2013-08-30T08:00:00Z
Fatalities                                                            NaN
Featured                                                            False
Final                                                                True
FuelType                                                              NaN
Helicopters                                                           NaN
Injuries                                                              NaN
Latitude                                                            39.12
Location                          Deadwood Ridge, northeast of Foresthill
Longitude                                                         -120.65
MajorIncident                                                       False
Name                                                        American Fire
PercentContained                                                      100
PersonnelInvolved                                                     NaN
Public                                                               True
SearchDescription       The American Fire burned in August 2013 off De...
SearchKeywords          American Fire, August 2013, Deadwood Ridge, Fo...
Started                                              2013-08-10T16:30:00Z
Status                                                          Finalized
StructuresDamaged                                                     NaN
StructuresDestroyed                                                   NaN
StructuresEvacuated                                                   NaN
StructuresThreatened                                                  NaN
UniqueId                             8213f5c7-34fa-403b-a4bc-da2ace6e6625
Updated                                              2013-08-30T08:00:00Z
WaterTenders                                                          NaN
Name: 3, dtype: object

In [30]:
nombre=['Eli','Almu','Bea', 'Luis','Jorge', 'Hector']
edad=[32,29,30,33,27,29]
personas=pd.DataFrame(edad, columns=['edad'], index=nombre)
print(personas)

        edad
Eli       32
Almu      29
Bea       30
Luis      33
Jorge     27
Hector    29

In [31]:
personas['edad']

Eli       32
Almu      29
Bea       30
Luis      33
Jorge     27
Hector    29
Name: edad, dtype: int64

In [32]:
personas.loc['Eli']

edad    32
Name: Eli, dtype: int64

In [47]:
del incendios['Name']

In [48]:
incendios.pop('Active')

0       False
1       False
2       False
3       False
4       False
        ...
1631    False
1632    False
1633    False
1634    False
1635    False
Name: Active, Length: 1636, dtype: bool

In [49]:
incendios.columns

Index(['AcresBurned', 'AdminUnit', 'AirTankers', 'ArchiveYear',
       'CalFireIncident', 'CanonicalUrl', 'ConditionStatement',
       'ControlStatement', 'Counties', 'CountyIds', 'CrewsInvolved', 'Dozers',
       'Engines', 'Extinguished', 'Fatalities', 'Featured', 'Final',
       'FuelType', 'Helicopters', 'Injuries', 'Latitude', 'Location',
       'Longitude', 'MajorIncident', 'PercentContained', 'PersonnelInvolved',
       'Public', 'SearchDescription', 'SearchKeywords', 'Started', 'Status',
       'StructuresDamaged', 'StructuresDestroyed', 'StructuresEvacuated',
       'StructuresThreatened', 'UniqueId', 'Updated', 'WaterTenders'],
      dtype='object')

In [51]:
incendios.drop(0)

,AcresBurned,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,CountyIds,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
1,30274.0,USFS Angeles National Forest/Los Angeles Count...,NaN,2013,True,/incidents/2013/5/30/powerhouse-fire/,NaN,NaN,Los Angeles,19,...,"Powerhouse Fire, May 2013, June 2013, Angeles ...",2013-05-30T15:28:00Z,Finalized,NaN,NaN,NaN,NaN,bf37805e-1cc2-4208-9972-753e47874c87,2013-06-08T18:30:00Z,NaN
2,27531.0,CAL FIRE Riverside Unit / San Bernardino Natio...,NaN,2013,True,/incidents/2013/7/15/mountain-fire/,NaN,NaN,Riverside,33,...,"Mountain Fire, July 2013, Highway 243, Highway...",2013-07-15T13:43:00Z,Finalized,NaN,NaN,NaN,NaN,a3149fec-4d48-427c-8b2c-59e8b79d59db,2013-07-30T18:00:00Z,NaN
3,27440.0,Tahoe National Forest,NaN,2013,False,/incidents/2013/8/10/american-fire/,NaN,NaN,Placer,31,...,"American Fire, August 2013, Deadwood Ridge, Fo...",2013-08-10T16:30:00Z,Finalized,NaN,NaN,NaN,NaN,8213f5c7-34fa-403b-a4bc-da2ace6e6625,2013-08-30T08:00:00Z,NaN
4,24251.0,Ventura County Fire/CAL FIRE,NaN,2013,True,/incidents/2013/5/2/springs-fire/,Acreage has been reduced based upon more accur...,NaN,Ventura,56,...,"Springs Fire, May 2013, Highway 101, Camarillo...",2013-05-02T07:01:00Z,Finalized,6.0,10.0,NaN,NaN,46731fb8-3350-4920-bdf7-910ac0eb715c,2013-05-11T06:30:00Z,11.0
5,22992.0,Sierra National Forest,NaN,2013,False,/incidents/2013/7/22/aspen-fire/,NaN,NaN,Fresno,10,...,"217 Aspen Fire, July 2013, Big Creek, Fresno ...",2013-07-22T22:15:00Z,Finalized,NaN,NaN,NaN,NaN,bee8c339-4f26-4b78-a5b4-a8a0ebdb8786,2013-09-24T20:15:00Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,9.0,CAL FIRE / Riverside County Fire,NaN,2019,True,/incidents/2019/10/10/eagle-fire/,NaN,NaN,Riverside,33,...,NaN,2019-10-10T12:08:00Z,Finalized,NaN,NaN,NaN,NaN,6e93b252-99a3-4214-9921-238373b17535,2019-10-10T18:11:59.733Z,NaN
1632,2.0,CAL FIRE Nevada-Yuba-Placer Unit,NaN,2019,True,/incidents/2019/6/28/long-fire/,NaN,NaN,Nevada,29,...,NaN,2019-06-28T15:03:04Z,Finalized,NaN,NaN,NaN,NaN,b38c0563-b321-431b-9174-6336c5a0d449,2019-06-30T15:52:01.023Z,NaN
1633,NaN,Yolo County Fire Protection District,NaN,2019,False,/incidents/2019/11/25/cashe-fire/,NaN,NaN,Yolo,57,...,NaN,2019-11-25T12:02:02Z,Finalized,NaN,NaN,NaN,NaN,9c26f915-1b33-422d-b30a-9eb4da6fd729,2019-12-03T16:35:20.93Z,NaN
1634,NaN,Camp Pendleton Marine Corps Base,NaN,2019,False,/incidents/2019/10/22/oak-fire/,NaN,NaN,San Diego,37,...,NaN,2019-10-22T19:20:44Z,Finalized,NaN,NaN,NaN,NaN,7264a106-e0f4-41de-8fd0-3f9110431e28,2019-11-21T12:21:28.58Z,NaN
1635,NaN,Bureau of Indian Affairs,NaN,2019,False,/incidents/2019/10/14/johnson-fire/,"As of 10:00 p.m. on 10/16, the fire is 90% con...",NaN,Riverside,33,...,NaN,2019-10-14T15:32:20Z,Inactive,NaN,NaN,NaN,NaN,8bf75401-999f-42bd-8c0a-8db508591545,2019-10-30T10:14:19.58Z,NaN

In [52]:
incendios[0:10]

,AcresBurned,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,CountyIds,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
0,257314.0,Stanislaus National Forest/Yosemite National Park,NaN,2013,True,/incidents/2013/8/17/rim-fire/,NaN,NaN,Tuolumne,55,...,"Rim Fire, Stanislaus National Forest, Yosemite...",2013-08-17T15:25:00Z,Finalized,NaN,NaN,NaN,NaN,5fb18d4d-213f-4d83-a179-daaf11939e78,2013-09-06T18:30:00Z,NaN
1,30274.0,USFS Angeles National Forest/Los Angeles Count...,NaN,2013,True,/incidents/2013/5/30/powerhouse-fire/,NaN,NaN,Los Angeles,19,...,"Powerhouse Fire, May 2013, June 2013, Angeles ...",2013-05-30T15:28:00Z,Finalized,NaN,NaN,NaN,NaN,bf37805e-1cc2-4208-9972-753e47874c87,2013-06-08T18:30:00Z,NaN
2,27531.0,CAL FIRE Riverside Unit / San Bernardino Natio...,NaN,2013,True,/incidents/2013/7/15/mountain-fire/,NaN,NaN,Riverside,33,...,"Mountain Fire, July 2013, Highway 243, Highway...",2013-07-15T13:43:00Z,Finalized,NaN,NaN,NaN,NaN,a3149fec-4d48-427c-8b2c-59e8b79d59db,2013-07-30T18:00:00Z,NaN
3,27440.0,Tahoe National Forest,NaN,2013,False,/incidents/2013/8/10/american-fire/,NaN,NaN,Placer,31,...,"American Fire, August 2013, Deadwood Ridge, Fo...",2013-08-10T16:30:00Z,Finalized,NaN,NaN,NaN,NaN,8213f5c7-34fa-403b-a4bc-da2ace6e6625,2013-08-30T08:00:00Z,NaN
4,24251.0,Ventura County Fire/CAL FIRE,NaN,2013,True,/incidents/2013/5/2/springs-fire/,Acreage has been reduced based upon more accur...,NaN,Ventura,56,...,"Springs Fire, May 2013, Highway 101, Camarillo...",2013-05-02T07:01:00Z,Finalized,6.0,10.0,NaN,NaN,46731fb8-3350-4920-bdf7-910ac0eb715c,2013-05-11T06:30:00Z,11.0
5,22992.0,Sierra National Forest,NaN,2013,False,/incidents/2013/7/22/aspen-fire/,NaN,NaN,Fresno,10,...,"217 Aspen Fire, July 2013, Big Creek, Fresno ...",2013-07-22T22:15:00Z,Finalized,NaN,NaN,NaN,NaN,bee8c339-4f26-4b78-a5b4-a8a0ebdb8786,2013-09-24T20:15:00Z,NaN
6,20292.0,CAL FIRE Riverside Unit / San Bernardino Natio...,NaN,2013,True,/incidents/2013/8/7/silver-fire/,Firefighters closed the containment lines toda...,Hwy 243 remains closed between Twin Pines Road...,Riverside,33,...,"Silver Fire, August 2013, Popet Flats Road, Hi...",2013-08-07T14:05:00Z,Finalized,8.0,40.0,NaN,NaN,c400203b-a7fd-4bd8-803a-f3c74bc32a2b,2013-08-12T18:00:00Z,20.0
7,14754.0,Klamath National Forest,NaN,2013,False,/incidents/2013/7/31/salmon-river-complex/,NaN,NaN,Siskiyou,47,...,"210 Salmon River Complex, August 2013, July 20...",2013-07-31T22:00:00Z,Finalized,NaN,NaN,NaN,NaN,ba76c009-09c9-497c-b923-1ac8cf05c20d,2013-08-31T06:45:00Z,NaN
8,12503.0,Six Rivers National Forest,NaN,2013,False,/incidents/2013/8/10/corral-complex/,NaN,NaN,Humboldt,12,...,"Corral Complex, August 2013, Tish Tang Ridge, ...",2013-08-10T11:40:00Z,Finalized,NaN,NaN,NaN,NaN,f3dcbca8-f8ed-46d0-8f6e-9c7fc2fb03e6,2013-08-12T12:00:00Z,NaN
9,11429.0,CAL FIRE Tehama-Glenn Unit,NaN,2013,True,/incidents/2013/8/23/deer-fire/,Fire suppression repair will continue througho...,NaN,Tehama,52,...,"Deer Fire, August 2013, Tehama County, Deer Cr...",2013-08-23T14:15:00Z,Finalized,NaN,NaN,NaN,NaN,956dbcf6-db40-4b61-b235-4ede14738f1e,2013-08-29T16:45:00Z,8.0

In [53]:
columna_final=incendios.pop('Final')

In [54]:
incendios.columns

Index(['AcresBurned', 'AdminUnit', 'AirTankers', 'ArchiveYear',
       'CalFireIncident', 'CanonicalUrl', 'ConditionStatement',
       'ControlStatement', 'Counties', 'CountyIds', 'CrewsInvolved', 'Dozers',
       'Engines', 'Extinguished', 'Fatalities', 'Featured', 'FuelType',
       'Helicopters', 'Injuries', 'Latitude', 'Location', 'Longitude',
       'MajorIncident', 'PercentContained', 'PersonnelInvolved', 'Public',
       'SearchDescription', 'SearchKeywords', 'Started', 'Status',
       'StructuresDamaged', 'StructuresDestroyed', 'StructuresEvacuated',
       'StructuresThreatened', 'UniqueId', 'Updated', 'WaterTenders'],
      dtype='object')

In [56]:
columna_final

0        True
1        True
2        True
3        True
4        True
        ...
1631     True
1632     True
1633     True
1634     True
1635    False
Name: Final, Length: 1636, dtype: bool

In [58]:
incendios['Final']=columna_final

In [59]:
incendios.columns

Index(['AcresBurned', 'AdminUnit', 'AirTankers', 'ArchiveYear',
       'CalFireIncident', 'CanonicalUrl', 'ConditionStatement',
       'ControlStatement', 'Counties', 'CountyIds', 'CrewsInvolved', 'Dozers',
       'Engines', 'Extinguished', 'Fatalities', 'Featured', 'FuelType',
       'Helicopters', 'Injuries', 'Latitude', 'Location', 'Longitude',
       'MajorIncident', 'PercentContained', 'PersonnelInvolved', 'Public',
       'SearchDescription', 'SearchKeywords', 'Started', 'Status',
       'StructuresDamaged', 'StructuresDestroyed', 'StructuresEvacuated',
       'StructuresThreatened', 'UniqueId', 'Updated', 'WaterTenders', 'Final'],
      dtype='object')

In [63]:
####### DF
#     Fecha1   Fecha2  Fecha3  Fecha4
# v1
# v2
# v3

fechas=('F1','F2','F3','F4','F5')
v1=(2,5,4,7,8)
v2=(4,7,2,7,9)

mediciones=pd.DataFrame((v1,v2),columns=fechas)
mediciones

   F1  F2  F3  F4  F5
0   2   5   4   7   8
1   4   7   2   7   9

In [64]:
mediciones['F6']=(3,4)
mediciones

   F1  F2  F3  F4  F5  F6
0   2   5   4   7   8   3
1   4   7   2   7   9   4

In [100]:
nueva_fila= pd.DataFrame(   ( (5,5,5,5,5,5),) , columns=mediciones.columns   ,index=(mediciones.index.stop,)  )
print(nueva_fila)
mediciones=mediciones.append(    nueva_fila    )

   F1  F2  F3  F4  F5  F6
2   5   5   5   5   5   5

In [97]:
pd.DataFrame(   ( (5,5,5,5,5,5),) , columns=mediciones.columns   ,index=(mediciones.index.stop,) )
#

   F1  F2  F3  F4  F5  F6
2   5   5   5   5   5   5

In [75]:
(5,5,5,5,5,5)

(5, 5, 5, 5, 5, 5)

In [77]:
((5,5,5,5,5,5),)

((5, 5, 5, 5, 5, 5),)

In [81]:
(1,2)   # <<<----- Lista

(1, 2)

In [87]:
 (   (1,2) ,  )

((1, 2),)

In [85]:
3*(4+2)  # ()  <<--- Prioriza: AgrupaciÃ³n

18

In [96]:
print(mediciones.index.stop)

2

In [101]:
mediciones

   F1  F2  F3  F4  F5  F6
0   2   5   4   7   8   3
1   4   7   2   7   9   4
2   5   5   5   5   5   5

In [104]:
mediciones=mediciones.drop(2)

In [105]:
mediciones

   F1  F2  F3  F4  F5  F6
0   2   5   4   7   8   3
1   4   7   2   7   9   4